### ISSUE TITLE
Missing buffer management for large messages

### ISSUE THREAD

**Issue by bluetech** [1tgr/rust-websocket-codec#1]
I read through some parts of this crate, it is very well written.

I may be missing something, and didn't try to verify it empirically. I think the `Decoder` might perform excessive reallocations given large messages. By default, tokio's `Framed` uses an 8kb buffer ([link](https://github.com/tokio-rs/tokio/blob/b4cb3226ab0c3cc6af272ba27ce176c84c79b73b/tokio-io/src/_tokio_codec/framed_read.rs#L24)), but from there after it's the `Decoder`'s responsibility to reserve enough capacity in the buffer for the anticipated messages. Looking at the code below, it does not appear to be doing so:

https://github.com/1tgr/rust-websocket-codec/blob/95f484aee96f5686470f8cae3685eee16882d9a5/src/message.rs#L140-L150

So what would happen given a large message, in the worse case, is an excruciating loop of tokio increasing the buffer capacity [by 1](https://github.com/tokio-rs/tokio/blob/b4cb3226ab0c3cc6af272ba27ce176c84c79b73b/tokio-io/src/_tokio_codec/framed_read.rs#L205-L208) each iteration, and the `Decoder` returning `Ok(None)`.

My suggestion is:

- If not enough bytes for the header, reserve some 512 bytes which should be enough for all headers even with extensions and whatnot.
- If enough to read the header and the length, but not enough to read the data, reserve enough for the header+data, and also enough for the next frame header, to avoid one `reserve` call in the next frame.

**Comment by 1tgr** [comment]
Thanks for the detailed analysis and writeup! I'll implement the changes along with a test that drives the decoder the same way that FramedRead would.
